// <js constant> : { "bxb": <Bixby Enum Symbol>, "tmdbId": <The Movie DB ID> }
module.exports = {
  "Horror": { "bxb": "Horror", "tmdbId": 27 },
  "Thriller": { "bxb": "Thriller", "tmdbId": 53 },
  "Mystery": { "bxb": "Mystery", "tmdbId": 9648 },
  "Crime": { "bxb": "Crime", "tmdbId": 80 },
  "Adventure": { "bxb": "Adventure", "tmdbId": 12 },
  "Action": { "bxb": "Action", "tmdbId": 28 },
  "Fantasy": { "bxb": "Fantasy", "tmdbId": 14 },
  "ScienceFiction": { "bxb": "ScienceFiction", "tmdbId": 878 },
  "Family": { "bxb": "Family", "tmdbId": 10751 },
  "Animation": { "bxb": "Animation", "tmdbId": 16 },
  "Comedy": { "bxb": "Comedy", "tmdbId": 35 },
  "Romance": { "bxb": "Romance", "tmdbId": 10749 },
  "Western": { "bxb": "Western", "tmdbId": 37 },
  "Drama": { "bxb": "Drama", "tmdbId": 18 },
  "History": { "bxb": "History", "tmdbId": 36 },
  "War": { "bxb": "War", "tmdbId": 10752 },
  "Documentary": { "bxb": "Documentary", "tmdbId": 99 },
  "Music": { "bxb": "Music", "tmdbId": 10402 },
}